#!/bin/bash

while read local_ref local_sha remote_ref remote_sha
do
    branch_name=$(echo "$local_ref" | cut -d / -f 3)
    pattern="^(BIFO|AVVIK)-[0-9]{1,3}$|^(NOISSUE|main)$"

    if ! [[ $branch_name =~ $pattern ]]; then
        echo "Error: Branch name '$branch_name' does not match the required pattern '$pattern'"
        exit 1
    fi
done

exit 0